apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: workstream-test-2
    app.kubernetes.io/part-of: app-workstream-test-2
  name: workstream-test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workstream-test-2
      app.kubernetes.io/part-of: app-workstream-test-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: workstream-test-2
        app.kubernetes.io/part-of: app-workstream-test-2
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/quick-yen-359707/poc/workstream-test-2:latest
        imagePullPolicy: Always
        name: workstream-test-2
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      serviceAccountName: default
status: {}