apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: workstream-test-2
    app.kubernetes.io/part-of: workstream-test-2
  name: workstream-test-2
spec:
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: 3000-tcp
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: workstream-test-2
    app.kubernetes.io/part-of: app-workstream-test-2
status:
  loadBalancer: {}