name: Docker-GCP
on:
  push:
    branches:
      - main
      - feature-new
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud
        #uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure docker for GCP europe-west2-docker.pkg.dev
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build docker image
        run: docker build -t europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/poc/workstream-test-2:latest .

      - name: Push to Google Artefact Registry
        run: docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/poc/workstream-test-2:latest
